### ISSUE TITLE
Remove and ignore the bin/ folder in git

### ISSUE THREAD

**Issue by svenkeidel** [monto-editor/services-python#1]
Hi,

I saw that you committed some binary files to the version control system. Generated files should never be committed to the repository.

To remove the `bin/` folder, execute the command

``` shell
git rm -r bin/
```

To permanently ignore files in this folder, execute the command

``` shell
echo "bin/" >> .gitignore
```

Finally you have to commit and push these changes.

Best,
Sven

**Comment by skockmann** [comment]
Hey,

thx for your advice. I have to admit, it was my first time pushing an initial repository. I might lack a bit more in knowledge of 'good practice'. So, thx for the help.

greetz,
Stefan
